# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
required = ["k8s.io/code-generator/cmd/client-gen"]

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.16.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.16.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.16.0"

[prune]
  go-tests = true
  non-go = true
